version: '3.8'

services:
  backend:
    build: .
    container_name: express-email-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo/mydb
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:5
    container_name: express-email-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
